/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "sidd_factorial.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

factorial_out *
factorialproc_1(factorial_in *argp, CLIENT *clnt)
{
	static factorial_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FACTORIALPROC,
		(xdrproc_t) xdr_factorial_in, (caddr_t) argp,
		(xdrproc_t) xdr_factorial_out, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
