/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sidd_factorial.h"

bool_t
xdr_factorial_in (XDR *xdrs, factorial_in *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->arg1))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_factorial_out (XDR *xdrs, factorial_out *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->resl))
		 return FALSE;
	return TRUE;
}
